spring:
    profiles:
        active: dev_aurora
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://jeabdb.cluster-caipzgwbnva8.ap-southeast-1.rds.amazonaws.com/JeabDB
        username: administrator
        password: n2nadmiN
        hikari:
            auto-commit: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.jdbc.lob.non_contextual_creation: true

cloud:
    aws:
        credentials:
            accessKeyId:
            secretKey: 
        instanceProfile: true
        region:
            static: ap-southeast-1

        rds:
            #dbInstanceIdentifier: jeabdb
            jeabdb:
                username: administrator
                password: n2nadmiN
                # readReplicaSupport: true
                databaseName: JeabDB
